services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfilebe
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres_user:postgres_password@db:5432/postgres_db
    depends_on:
      - db
    volumes:
      - ./frontend:/frontend  
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfilefe
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html  
      - /usr/share/nginx/html/node_modules
  db:
    image: postgis/postgis:15-3.3
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql  
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password

volumes:
  postgres_data:
