services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfilebe
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres_user:postgres_password@db:5432/postgres_db
    depends_on:
      - db
    volumes:
      - ./frontend:/frontend  # Mappa la cartella frontend all'interno del container backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfilefe
    ports:
      - "8080:80"

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password

volumes:
  postgres_data:
