version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfilebe
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/homezone

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfilefe
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: homezone
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
