apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: home-zone-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-backend-image:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: DATABASE_URL
              value: "postgresql://user:password@db:5432/homezone"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: home-zone-analyzer
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
